server:
    port: 9501
spring:
    application:
        name: cloud-consumer
    zipkin:
        base-url: http://localhost:9411/
        enabled: true
        locator:
            discovery:
                enabled: true